/**
* @File Name : ChatbotController.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : November 28, 2024
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | November 28, 2024 |   | Initial Version
**/

public class ChatbotController {
	@AuraEnabled
	Public static void LightningStudio(){
		System.debug('Lightning Studio');
	}
}