/**
* @File Name : HomeLoanController.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : October 21, 2024
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | October 21, 2024 |   | Initial Version
**/

public class HomeLoanController {
	@AuraEnabled
	Public static void LightningStudio(){
		System.debug('Lightning Studio');
	}
}