public class YoutubeClass {
/*
        //Declaration and Initialization of a "List" in APEX !
            
            //Declaration and Initialization in a line
            List<String> myList = new List<String>();
        // ______part 1_______  =  _____part 2______

            //Let's breakdown each and every Element of "List<String> myList = new List<String>();" !!!!

            //Declaration of "List" in APEX (part 1)
            List<String> myList ;
            
            //Initialization of "List" in APEX (part 2)
            myList = new List<String>();


            List //--> Keyword / Class in APEX
                
            "< placeholder >"  
                // "< >" angle brackets are used to indicate the generic types.
                //Generics allow you to define classes, interfaces,or methods.
                
                //"placeholder" >>>> use to define data types.
                
            myList //--> instance Variable Name (expected to store collection of strings)
                
            "=" //--> assignment Operator

            new //--> Keyword to create a new Instance

            ()  //---> Indicates it's a constructor call
            
            "List<String> myList;"
                // declares a instance variable of  "List of String" type

            "new List<String>()"
                //-->Creates a new Instance of "List" Class with a specified type of parameter of "String".
                //It calls a constructor to initialize a new, empty list of Strings.

            // part 1 +part 2 together constitue the initialization and declaration of list in apex
              List<String> myList = new List<String>();*/
}